/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lendmn.api;

public class Service {
    protected String clientId;
    protected String secret;
    protected String accessToken;

    public Service(String clientId, String secret) {
      this.clientId = clientId;
      this.secret = secret;
    }

    public void setAccessToken(String accessToken) {
      this.accessToken = accessToken;
    }

    public String getAccessToken() {
      return this.accessToken;
    }


}
