/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lendmn.api;

import org.junit.Test;
import static org.junit.Assert.*;

public class ServiceTest {
    @Test public void testSomeLibraryMethod() {
        Service classUnderTest = new Service("clienId", "some_secret");
        classUnderTest.setAccessToken("testTOKEN");
        assertEquals("someLibraryMethod should return 'testTOKEN'", "testTOKEN", classUnderTest.getAccessToken());
    }
}
